javascripts:
  global:
    - public/javascripts/jquery-1.5.js
    - public/javascripts/jquery-ui-1.8rc3.custom.min.js
    - public/javascripts/jquery.plugins/*.js
    - public/javascripts/theme/jquery.data_input.pack.js
    - public/javascripts/theme/*.js
    - public/javascripts/rails.js
    - public/javascripts/helpers.js
    - public/javascripts/sammy-latest.min.js
    - public/javascripts/js-model-0.10.0.min.js
    - public/javascripts/sammy.models/*.js
    - public/javascripts/sammy.plugins/*.js

  templates:
    - app/views/**/*.jst