javascripts:
  global:
    - public/javascripts/jquery-1.4.4.min.js
    - public/javascripts/jquery-ui-1.8rc3.custom.min.js
    - public/javascripts/jquery.plugins/*.js
    - public/javascripts/theme/jquery.data_input.pack.js
    - public/javascripts/theme/*.js
    - public/javascripts/rails.js
    - public/javascripts/helpers.js
    - public/javascripts/sammy-latest.min.js
    - public/javascripts/sammy.plugins/*.js
    - app/views/**/*.jst
package_assets: always