development: &development
  adapter: postgresql
  database: geocms_development
  host: localhost
  pool: 5
  username: o1
  password: com99123
  timeout: 5000
  encoding: utf8
  min_messages: warning
  template: template_postgis

beta:
  <<: *development
  database: geocms_beta
  username: deployment
  password: FireDrake[1981]

test:
  <<: *development
  database: geocms_test

production:
  <<: *development
  host: galileo.codeifier.com
  database: cms_production
  username: deployment
  password: FireDrake[1981]

cucumber:
  <<: *development
  database: geocms_test
