development: &development
  adapter: postgresql
  database: cms_production
  host: galileo.codeifier.com
  pool: 5
  username: deployment
  password: FireDrake[1981]
  timeout: 5000
  encoding: utf8
  min_messages: warning
  template: template_postgis

test:
  <<: *development
  database: geocms_test

production:
  <<: *development
  host: galileo.codeifier.com
  database: cms_production
  username: deployment
  password: FireDrake[1981]