development: &development
  adapter: postgresql
  database: cms_development
  host: localhost
  pool: 5
  username: o1
  password: com99123
  timeout: 5000
  encoding: utf8
  min_messages: warning
  template: template_postgis

alpha:
  <<: *development

beta:
  <<: *production

test: &test
  <<: *development
  database: cms_test

production: &production
  <<: *development
  database: cms_production

cucumber:
  <<: *test
