development: &development
  adapter: postgresql
  database: geocms_development
  host: localhost
  pool: 5
  username: o1
  password: com99123
  timeout: 5000
  encoding: utf8
  min_messages: warning
  template: template_postgis

test: &test
  <<: *development
  database: geocms_test

cucumber:
  <<: *test