development:
  adapter: postgresql
  database: cms_development
  host: localhost
  pool: 5
  username: o1
  password: com99123
  timeout: 5000
  encoding: utf8
  min_messages: warning
  template: template_postgis

staging:
  adapter: postgresql
  database: geocms_staging
  host: localhost
  pool: 5
  username: o1
  password: com99123
  timeout: 5000
  encoding: utf8
  min_messages: warning
  template: template_postgis

test: &test
  adapter: postgresql
  database: cms_test
  pool: 5
  timeout: 5000
  username: o1
  password: com99123
  encoding: utf8
  host: localhost
  encoding: utf8
  min_messages: warning
  template: template_postgis

production:
  host: localhost
  min_messages: warning
  adapter: postgresql
  database: cms_production
  pool: 5
  username: o1
  password: com99123
  timeout: 5000
  encoding: utf8
  template: template_postgis

cucumber:
  <<: *test
